/**
 * RiseIQ — 13 Course Catalogue
 * discipline: matches DISCIPLINES id
 * requiredPlan: "free" | "pro" | "team"
 * href: where "Start Course" opens (in new tab per Rule 3)
 */

export const COURSES = [
  // ── Language ─────────────────────────────────────────────────────────
  {
    id: "ielts-general",
    slug: "ielts-general",
    title: "IELTS General Training",
    subtitle: "Band 7+ in Reading, Writing, Listening & Speaking",
    discipline: "language",
    emoji: "📝",
    color: "#1DB8A4",
    level: "Beginner → Advanced",
    duration: "8 weeks",
    lessons: 48,
    students: 1240,
    rating: 4.9,
    requiredPlan: "free",
    featured: true,
    synapseBrain: true,
    description:
      "The most complete IELTS General Training prep on RiseIQ. Timed practice for all four skills with instant Synapse Brain feedback on every essay.",
    href: "/dashboard",   // existing IELTS dashboard
    tags: ["IELTS", "English", "Exam Prep"],
  },
  {
    id: "ielts-academic",
    slug: "ielts-academic",
    title: "IELTS Academic",
    subtitle: "University and professional registration",
    discipline: "language",
    emoji: "🎓",
    color: "#1DB8A4",
    level: "Intermediate → Advanced",
    duration: "8 weeks",
    lessons: 44,
    students: 890,
    rating: 4.8,
    requiredPlan: "pro",
    synapseBrain: true,
    description:
      "Task 1 graph descriptions, Task 2 academic essays, and complex reading passages — all with AI-powered scoring.",
    href: "/dashboard",
    tags: ["IELTS", "Academic", "University"],
  },
  {
    id: "business-english",
    slug: "business-english",
    title: "Business English",
    subtitle: "Professional communication for the workplace",
    discipline: "language",
    emoji: "💬",
    color: "#1DB8A4",
    level: "Intermediate",
    duration: "6 weeks",
    lessons: 36,
    students: 650,
    rating: 4.7,
    requiredPlan: "pro",
    synapseBrain: true,
    description:
      "Emails, presentations, negotiations, and meetings — learn the English that gets things done at work.",
    href: "/practice/writing",
    tags: ["Business", "English", "Professional"],
  },
  {
    id: "french-basics",
    slug: "french-basics",
    title: "French Basics",
    subtitle: "Start speaking French with confidence",
    discipline: "language",
    emoji: "🇫🇷",
    color: "#1DB8A4",
    level: "Beginner",
    duration: "4 weeks",
    lessons: 24,
    students: 430,
    rating: 4.6,
    requiredPlan: "pro",
    description:
      "Greetings, travel phrases, and everyday conversation — your first steps into French.",
    href: "/courses/french-basics",
    tags: ["French", "Language", "Beginner"],
  },

  // ── Data & Analytics ─────────────────────────────────────────────────
  {
    id: "python-data",
    slug: "python-data",
    title: "Python for Data",
    subtitle: "Pandas, NumPy, and data visualization",
    discipline: "data",
    emoji: "🐍",
    color: "#6366F1",
    level: "Beginner → Intermediate",
    duration: "10 weeks",
    lessons: 60,
    students: 780,
    rating: 4.8,
    requiredPlan: "pro",
    synapseBrain: true,
    description:
      "Learn Python from scratch through real datasets. Master Pandas, NumPy, Matplotlib, and build your first ML model.",
    href: "/courses/python-data",
    tags: ["Python", "Data Science", "Analytics"],
  },
  {
    id: "excel-mastery",
    slug: "excel-mastery",
    title: "Excel Mastery",
    subtitle: "Pivot tables, VLOOKUP, dashboards & macros",
    discipline: "data",
    emoji: "📊",
    color: "#6366F1",
    level: "Beginner → Advanced",
    duration: "5 weeks",
    lessons: 30,
    students: 1100,
    rating: 4.7,
    requiredPlan: "free",
    description:
      "From basic formulas to advanced macros — become the Excel expert your team relies on.",
    href: "/courses/excel-mastery",
    tags: ["Excel", "Spreadsheets", "Business"],
  },

  // ── Cloud & DevOps ────────────────────────────────────────────────────
  {
    id: "azure-fundamentals",
    slug: "azure-fundamentals",
    title: "Azure Fundamentals",
    subtitle: "AZ-900 certification prep",
    discipline: "cloud",
    emoji: "☁️",
    color: "#0EA5E9",
    level: "Beginner",
    duration: "4 weeks",
    lessons: 28,
    students: 560,
    rating: 4.8,
    requiredPlan: "pro",
    synapseBrain: true,
    description:
      "Prepare for the Microsoft AZ-900 exam. Covers cloud concepts, Azure services, security, and pricing.",
    href: "/courses/azure-fundamentals",
    tags: ["Azure", "Cloud", "Microsoft", "Certification"],
  },
  {
    id: "aws-essentials",
    slug: "aws-essentials",
    title: "AWS Essentials",
    subtitle: "EC2, S3, Lambda, and core services",
    discipline: "cloud",
    emoji: "🟠",
    color: "#0EA5E9",
    level: "Beginner → Intermediate",
    duration: "6 weeks",
    lessons: 36,
    students: 490,
    rating: 4.7,
    requiredPlan: "pro",
    description:
      "Get hands-on with Amazon Web Services. Build and deploy real applications using EC2, S3, RDS, and Lambda.",
    href: "/courses/aws-essentials",
    tags: ["AWS", "Cloud", "Amazon", "DevOps"],
  },

  // ── AI & Automation ───────────────────────────────────────────────────
  {
    id: "prompt-engineering",
    slug: "prompt-engineering",
    title: "Prompt Engineering",
    subtitle: "Get 10× results from AI models",
    discipline: "ai",
    emoji: "🧠",
    color: "#8B5CF6",
    level: "Beginner → Intermediate",
    duration: "3 weeks",
    lessons: 18,
    students: 920,
    rating: 4.9,
    requiredPlan: "free",
    synapseBrain: true,
    featured: true,
    description:
      "Master prompt design for Claude, GPT-4, Gemini and more. Chain-of-thought, few-shot, and system prompts explained.",
    href: "/courses/prompt-engineering",
    tags: ["AI", "Prompts", "Claude", "ChatGPT"],
  },
  {
    id: "chatgpt-for-work",
    slug: "chatgpt-for-work",
    title: "ChatGPT for Work",
    subtitle: "AI workflows for non-technical professionals",
    discipline: "ai",
    emoji: "⚡",
    color: "#8B5CF6",
    level: "Beginner",
    duration: "2 weeks",
    lessons: 12,
    students: 1350,
    rating: 4.8,
    requiredPlan: "free",
    description:
      "Use AI to write faster, summarize documents, draft emails, and automate repetitive tasks — no coding required.",
    href: "/courses/chatgpt-for-work",
    tags: ["AI", "Productivity", "No-code"],
  },

  // ── Personal Growth ───────────────────────────────────────────────────
  {
    id: "public-speaking",
    slug: "public-speaking",
    title: "Public Speaking",
    subtitle: "Speak with clarity, confidence, and impact",
    discipline: "growth",
    emoji: "🎤",
    color: "#F5A623",
    level: "Beginner → Intermediate",
    duration: "4 weeks",
    lessons: 24,
    students: 670,
    rating: 4.7,
    requiredPlan: "pro",
    synapseBrain: true,
    description:
      "Overcome anxiety and deliver presentations that move audiences. From storytelling to vocal delivery.",
    href: "/courses/public-speaking",
    tags: ["Communication", "Speaking", "Leadership"],
  },
  {
    id: "time-management",
    slug: "time-management",
    title: "Time Management",
    subtitle: "Deep work, prioritization, and flow",
    discipline: "growth",
    emoji: "⏰",
    color: "#F5A623",
    level: "Beginner",
    duration: "2 weeks",
    lessons: 14,
    students: 840,
    rating: 4.6,
    requiredPlan: "free",
    description:
      "Apply proven frameworks — GTD, Pomodoro, time blocking — to get more done and stress less.",
    href: "/courses/time-management",
    tags: ["Productivity", "Focus", "Wellbeing"],
  },

  // ── Career ────────────────────────────────────────────────────────────
  {
    id: "resume-builder",
    slug: "resume-builder",
    title: "Resume Builder",
    subtitle: "ATS-friendly resumes that get interviews",
    discipline: "career",
    emoji: "📄",
    color: "#EF4444",
    level: "All levels",
    duration: "1 week",
    lessons: 8,
    students: 1580,
    rating: 4.9,
    requiredPlan: "free",
    synapseBrain: true,
    featured: true,
    description:
      "Synapse Brain reviews your resume in real time — keyword gaps, formatting, and impact statements fixed instantly.",
    href: "/courses/resume-builder",
    tags: ["Resume", "Job Search", "Career"],
  },
  {
    id: "interview-prep",
    slug: "interview-prep",
    title: "Interview Prep",
    subtitle: "STAR answers, salary negotiation & more",
    discipline: "career",
    emoji: "🤝",
    color: "#EF4444",
    level: "All levels",
    duration: "2 weeks",
    lessons: 16,
    students: 1120,
    rating: 4.8,
    requiredPlan: "pro",
    synapseBrain: true,
    description:
      "Mock interviews with Synapse Brain feedback. Master behavioural questions, salary negotiation, and offer evaluation.",
    href: "/courses/interview-prep",
    tags: ["Interview", "Career", "Negotiation"],
  },
];

export const getFeaturedCourses = () => COURSES.filter((c) => c.featured);
export const getCourseBySlug = (slug) => COURSES.find((c) => c.slug === slug);
export const getCoursesByDiscipline = (disciplineId) =>
  COURSES.filter((c) => c.discipline === disciplineId);
